### ISSUE TITLE
Typos in english pot file

### ISSUE THREAD

**Issue by uaevuon** [TeamCemu/Cemu-Language#38]
![주석 2019-07-06 172414](https://user-images.githubusercontent.com/3542715/60753801-09c15a00-a013-11e9-83c9-fd5a10e22332.jpg)

![주석 2019-07-06 173154](https://user-images.githubusercontent.com/3542715/60753888-fc589f80-a013-11e9-9cd9-2ad0671fb3db.jpg)

I think they're typos.
Right?

**Comment by Fs00** [comment]
It's not a typo, that's because the letter after the & is the one used for the menu keyboard shortcut. Feel free to remove the '&'s in your language if they aren't useful or don't make sense.

**Comment by uaevuon** [comment]
Thanks for the answer
